version: "2.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigmatech-xyz
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /go/src/gitlab.com/shagya/sigmatech-xyz
    command: go run main.go
    ports:
      - "${SMFLEADS_USER_PORT}:${SMFLEADS_USER_PORT}"
    expose:
      - "${SMFLEADS_USER_PORT}"
    environment:
      TZ: Asia/Jakarta
      VIRTUAL_HOST: https://docker-dev.shagya.co.id/sigmatech-xyz
    network_mode: host
    restart: always
networks:
  default:
